## Vignette: Carl Sandburg {-}

Carl August Sandburg (January 6, 1878 – July 22, 1967) was an American poet, biographer, journalist, and editor.
He won three Pulitzer Prizes: two for his poetry and one for his biography of Abraham Lincoln. During his lifetime, Sandburg was widely regarded as "a major figure in contemporary literature", especially for volumes of his collected verse, including Chicago Poems (1916), Cornhuskers (1918), and Smoke and Steel (1920).
He enjoyed "unrivaled appeal as a poet in his day, perhaps because the breadth of his experiences connected him with so many strands of American life",
and at his death in 1967, President Lyndon B. Johnson observed that "Carl Sandburg was more than the voice of America, more than the poet of its strength and genius. He was America."

This Vignette is an unnumbered section.  The running header for unnumbered sections is described in `krantz.cls` on a line customized by Bryan Clair.
You can find that line by searching for my name.

To test these custom section headers, let's make this vignette really long.

Bang pans!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!

Look around.

Bang pans again!
