# Methods

We can define theorem, example, and other blocks using Pandoc's *fenced div* syntax.

## Block structures

~~~
::: theorem
Random variables built from many independent events tend to be normal.
:::
~~~

Which becomes:

::: theorem
Random variables built from many independent events tend to be normal.
:::

Note that the various `\newtheorem` commands get put into the LaTeX preamble automatically
as long as your markdown document has one of bookdown's code block theorem-like structures.
As soon as the last one of those is eradicated, you need to put the `\newtheorem` definitions
into the `preamble.tex` file yourself, as you can see in this book's `preamble.tex`.

::: theorem
Binomial variables are approximately normal
:::

::: remark
By default, remarks are not numbered
:::

::: example
Examples and definitions are numbered together
:::

::: definition
This follows from the last example.
:::

::: example
This example contains an R block.
```{r}
1:10
```
:::

Nice!

Here is a more important theorem, so it's labeled for references using this syntax:

~~~
::: {.theorem #Lyapunov}
content of theorem
:::
~~~

Which looks the same, but is labeled.  

::: {.theorem #thm:Lyapunov}
Suppose $\{X_1, \ldots, X_n\}$ is a sequence of independent random variables, each with finite expected value $\mu_i$ and variance $\sigma_i^2$.
Define

\[ s_n^2 = \sum_{i=1}^n \sigma_i^2 \]

If for some $\delta > 0$, _Lyapunov’s condition_\index{Lyapunov's condition}

\[ \lim_{n\to\infty} \frac{1}{s_{n}^{2+\delta}} \sum_{i=1}^{n} \operatorname{E}\left[|X_{i} - \mu_{i}|^{2+\delta}\right] = 0 \]

is satisfied, then a sum of $\frac{X_i - \mu_i}{s_n}$ converges in distribution to a standard normal random variable, as $n$ goes to infinity:

\[ \frac{1}{s_n} \sum_{i=1}^{n} \left(X_i - \mu_i\right) \ \xrightarrow{d}\ N(0,1).\]
:::

## Referencing

You can reference theorem-like environments with ```\@ref(thm:Lyapunov)```. 

I would argue that Theorem \@ref(thm:Lyapunov) is a really good theorem.  Thanks, Dr. Lyapunov.

You can also reference across chapters. See Chapter \@ref(summary) for a link back to Lyapunov's theorem.

## Conclusion

The conclusion of this chapter also demonstrates the use of the `proof` environment:

::: theorem
Using fenced divs is superior to the block approach.
:::

::: proof
We prefer these fenced divs to the existing approach using code blocks.  Code blocks ruin the syntax highlighting in RStudio, cannot be nested or contain R code, and also have a nasty bug that breaks LaTeX output when the last thing in the theorem block is a list.
:::

## Exercises {-}
@doubles.
    a. Create a scatterplot of the number of doubles hit in each year from 1871-2015.
    b. Create a scatterplot of the number of doubles hit in each year from 1871-2015 in each league. Color the NL blue and the AL red.
@totalruns. Create boxplots for total runs scored per year in the AL and the NL from 1969-2015. 
@lifeba.
    a. Create a histogram of lifetime batting averages (H/AB) for all players who have at least 1000 career AB's. 
    b. In your histogram from (d), color the NL blue and the AL red. (If a player played in both the AL and NL, count their batting average in each league if they had more than 1000 AB's in that league.)
    
    &nbsp;
@birthmonth. Use the `People` data set from the `Lahman` library.
    a. Create a barplot of the birthmonths of all players. (Hint: `geom_bar()`)
    b. Create a barplot of the birth months of the players born in the USA after 1970.

Exercises @babycount - @jessie use the `babynames` data set from the `babynames` library, which you probably need to install.

@babycount. Make a line graph showing the total number of babies of each sex, plotted over time.
@namescount. Make a line graph showing the number of different names used for each sex, plotted over time.
@yourname. Make a line graph showing how many babies of your gender have your name, plotted over time.  If your name doesn't appear in the data, use the female name "Alexa".
@bryan. Make a line graph comparing the number of boys named Bryan and the number of boys named Brian from 1920 to the present.
@jessie. I wish that I had Jessie's girl, or maybe Jessie's guy? One one graph, plot the number of male and female babies named Jessie over time.

    Three time periods show up in the history of Jessie:

    - More male than female Jessie
    - More female than male Jessie
    - About the same male and female Jessie.
    
    Approximately what range of years does each time period span?

@assaults. Data scientist Kieran Healy created this widely circulated figure.
