# Theorem and related structures {#theorems}

We can define theorem, example, and other blocks using Pandoc's *fenced div* syntax.

## Basic usage

The syntax for a block is:

~~~
::: theorem
Random variables built from many independent events tend to be normal.
:::
~~~

Which becomes:

::: theorem
Random variables built from many independent events tend to be normal.
:::

Note that the various `\newtheorem` commands get put into the LaTeX preamble automatically
as long as your markdown document has one of bookdown's code block theorem-like structures.
As soon as the last one of those is eradicated, you need to put the `\newtheorem` definitions
into the `preamble.tex` file yourself, as you can see in this book's `preamble.tex`.

::: theorem
Binomial variables are approximately normal.  That's cool because:

1. Normal variables are easy
2. Discrete things are hard
:::

::: remark
By default, remarks are not numbered
:::

::: example
Examples and definitions are numbered together
:::

::: definition
This follows from the last example.
:::

::: example
This example contains an R block.
```{r}
1:10
```
:::

## Names and labels

Here is a more important theorem, so it's labeled for references using this syntax:

~~~
::: {.theorem #thm:Lyapunov data="Lyapunov's Central Limit Theorem"}
content of theorem
:::
~~~

Which looks the same, but is labeled for later reference and which has a name.

::: {.theorem #thm:Lyapunov data="Lyapunov's Central Limit Theorem"}
Suppose $\{X_1, \ldots, X_n\}$ is a sequence of independent random variables, each with finite expected value $\mu_i$ and variance $\sigma_i^2$.
Define

\[ s_n^2 = \sum_{i=1}^n \sigma_i^2 \]

If for some $\delta > 0$, _Lyapunov’s condition_\index{Lyapunov's condition}

\[ \lim_{n\to\infty} \frac{1}{s_{n}^{2+\delta}} \sum_{i=1}^{n} \operatorname{E}\left[|X_{i} - \mu_{i}|^{2+\delta}\right] = 0 \]

is satisfied, then a sum of $\frac{X_i - \mu_i}{s_n}$ converges in distribution to a standard normal random variable, as $n$ goes to infinity:

\[ \frac{1}{s_n} \sum_{i=1}^{n} \left(X_i - \mu_i\right) \ \xrightarrow{d}\ N(0,1).\]
:::

Here's another example where the name is different for HTML and LaTeX output, done with the header

~~~
::: {.theorem data-html="2&pi; Theorem" data-latex="$2\pi$ Theorem"}
~~~

::: {.theorem data-html="2&pi; Theorem" data-latex="$2\pi$ Theorem"}
A sufficient condition for Dehn filling on a cusped hyperbolic 3-manifold to result in a negatively curved 3-manifold.
:::

The `data-html` and `data-latex` take precedence over `data`, so you could use `data` to set a
default and then the output specific data settings to override that.

## Referencing

You can reference theorem-like environments with ```\@ref(thm:Lyapunov)```. 

I would argue that Theorem \@ref(thm:Lyapunov) is a really good theorem.  Thanks, Dr. Lyapunov.

You can also reference across chapters. See Chapter \@ref(summary) for a link back to Lyapunov's theorem.

There's an example in the preface, it's Example \@ref(prefaceex)

## Conclusion

The conclusion of this chapter also demonstrates the use of the `proof` environment:

::: theorem
Using fenced divs is superior to the block approach.
:::

::: proof
We prefer these fenced divs to the existing approach using code blocks.  Code blocks ruin the syntax highlighting in RStudio, cannot be nested or contain R code, and also have a nasty bug that breaks LaTeX output when the last thing in the theorem block is a list.
:::

## Exercises {-}

::: exercise
Run 8 laps.
:::

---------
Exercises \@ref(ex:firsthiit) - \@ref(ex:lasthiit) are HIIT.

::: {.exercise #ex:firsthiit}
Explode off the ground and change legs in the air on each rep.

a. Work 20 seconds.
b. Rest 10 seconds.
:::

::: exercise
Run on the spot, bringing your knees as high as possible.
:::

::: {.exercise #ex:lasthiit}
a. Work 20 seconds.
b. Rest 10 seconds.
:::
