# Dance

```{r echo=FALSE}
suppressMessages(suppressWarnings(library(dplyr)))
includeSolutions <- TRUE
```

Some _significant_ \index{significant} applications are demonstrated in this chapter.

::: definition
Daft Punk\index{daft punk} is a French\index{French} electronic music duo formed in Paris in 1993 by Guy-Manuel de Homem-Christo and Thomas Bangalter.
:::

Daft Punk achieved popularity in the late 1990s as part of the French house movement; they also had success in the years following, combining elements of house music with funk, techno, disco, rock and synthpop. They have worn ornate helmets and gloves to assume robot personas in most public appearances since 1999[10] and rarely grant interviews or appear on television. The duo were managed from 1996 to 2008 by Pedro Winter (also known as Busy P), the head of Ed Banger Records.

Here is a `tryit` block:

::: tryit
Try dancing to "Lose Yourself to Dance".  According to Pharrell, you should "feel like walking down the street in the middle of the night in London and it's 1984, 1985".
:::

Here is an alert.

::: alert
Single line alerts don't look great in PDF, and mysteriously depend on spacing in the source.
:::

It is possible to nest blocks. The extra `:` characters are optional.  Here is a tryit nested within an example.

::: example
One more time

We're gonna celebrate

:::: alert

Oh yeah, all right

::::

Don't stop the dancing

:::

Why do they wear masks?  Here's a quote:

I think people understand what we are doing. I know many people who maybe like the way we are handling things. People understand that you don't need to be on the covers of magazines with your face to make good music. Painters or other artists, you don't know them but you know what they are doing. We are very happy that the concept in itself is becoming famous. In France, you speak of Daft Punk and I'm sure millions of people have heard it, but less than a few thousand people know our face—which is the thing we're into. We control it, but it's not us physically, our persons. We don't want to run into people who are the same age as us, shaking our hand and saying, 'Can I have your autograph?' because we think we're exactly like them. Even girls, they can fall in love with your music, but not with you. You don't always have to compromise yourself to be successful. The playing with masks is just to make it funnier. Pictures can be boring.

::: alert
This alert is on a different page.  And it's long enough that it wraps to a few lines.

Daft Punk continued to wear the robot costumes in their live performances at the 2008, 2014 and 2017 Grammy Awards, with variations in clothing. During the 2014 ceremony, they also accepted their awards on stage in the outfits, with Pharrell and Paul Williams speaking on the duo's behalf.
:::

## Exercises {-}

::: {.exercise #ex:work}
Work it\index{daft punk!work it}
:::

::: {.exercise #ex:make}
Make it\index{daft punk!make it}
:::

::: {.exercise #ex:do}
Do it\index{daft punk!do it}
:::

--------------

Now what happens?

::: {.exercise #ex:us}
Makes us
:::

::: {.exercise #ex:better}
Harder, better, faster, stronger.
:::
