# Final Words {#summary}

Please answer question \@ref(ex:easy).  Question \@ref(ex:easy) should be and easy warmup for question \@ref(ex:skills). Answer question \@ref(ex:skills) before trying question \@ref(ex:hard).  Question \@ref(ex:impossible) doesn't actually exist.

::: example
This is an example.
:::

::: example
Another example.
:::

::: theorem
A theorem.
:::

::: definition
Let $A$ and $B$ be events in a sample space $S$. 

1. $A \cap B$ is the set of outcomes that are in  *both* $A$ and $B$.
2. $A \cup B$ is the set of outcomes that are in *either* $A$ or $B$ (or both).
3. $\overline{A}$ is the set of outcomes that are *not* in $A$ (but are in $S$). 
4. $A \setminus B$ is the set of outcomes that are in $A$ and not in $B$.
:::

::: example
Third example.
:::

::: definition
I like my TVs to have high definition.
:::

Now you're ready for questions \@ref(ex:easy) and \@ref(ex:skills), but probably need to study more before working question \@ref(ex:hard).

You might refer back to Theorem \@ref(thm:Lyapunov) if you want to learn.

## kables

Test that fenced divs are compatible with kable.

::: example
This example has a kable

```{r}
knitr::kable(table(discoveries))
```

It is inside an example.
:::

## Exercises {-}

Question \@ref(ex:easy) is easy.

::: {.exercise #ex:easy}
What is $S$?
:::

Questions \@ref(ex:hard) and \@ref(ex:impossible) are harder.

::: {.exercise #ex:skills}
Show $\overline{\overline{(A+B)}+C} = A \cap \overline{C} + B \cap \overline{C}$
:::

::: {.exercise #ex:hard}
Given a formula $F(A_1,\dotsc,A_n)$ made from $\cup$,$\cap$, and set complement, find events $A_1,\cdots,A_n$ so that the set $F(A_1,\dotsc,A_n)$ is nonempty.
:::
