--- 
#
# Book Metadata
#
title: "Bookdown Technical Demo"
author: "Bryan Clair"
date: "`r Sys.Date()`"

   # description field is metadata in the html files that will appear on
   # social media.  It does not appear in the book text.
description: >-
   Bookdown Technical Demo by Bryan Clair.
   This has all the technical features of Speegle, Clair "Foundations of Statistics with R".

site: bookdown::bookdown_site   # needed for R studio integraion (Build tab)

bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes

# Settings for CRC's krantz.cls
# (more specifically, Yihui Xie's mod of krantz.cls)
documentclass: krantz # use 'book' for default book documentclass
classoption: krantz2  # gives 5.5 x 8.5 page area.  Default is krantz1, 4.5 x 7.5

---

```{r include=FALSE}
# This works together with package-list.R to create an automatic
# list of packages used by the book.  That list turns into
# pacakages.bib for use in the References

packs <- c("bookdown","rmarkdown","knitr")
if (!is.null(packs)) {
  packfile <- file("package-list","a")
  writeLines(packs,packfile)
  close(packfile)
}
```
```{r include=FALSE, cache=FALSE}
# This script is set to run automatically at the end of each chapter
# in the _bookdown.yml configuration file

#
# It automatically writes all packages to the end of the file "package-list"
# which was first created in the index.Rmd file
#
packs <- .packages()
if (!is.null(packs)) {
  packfile <- file("package-list","a")
  writeLines(packs,packfile)
  close(packfile)
}
```
```{r include=FALSE, cache=FALSE}
# This script is set to run automatically at the end of each chapter
# in the _bookdown.yml configuration file

#
# It automatically writes all packages to the end of the file "package-list"
# which was first created in the index.Rmd file
#
packs <- .packages()
if (!is.null(packs)) {
  packfile <- file("package-list","a")
  writeLines(packs,packfile)
  close(packfile)
}
```
```{r include=FALSE, cache=FALSE}
# This script is set to run automatically at the end of each chapter
# in the _bookdown.yml configuration file

#
# It automatically writes all packages to the end of the file "package-list"
# which was first created in the index.Rmd file
#
packs <- .packages()
if (!is.null(packs)) {
  packfile <- file("package-list","a")
  writeLines(packs,packfile)
  close(packfile)
}
```
